//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CCModel", "FK_Race_Organization", "Organization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.Organization), "Race", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.Race), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_User_Organization", "Organization", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.Organization), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.User), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecord_Race", "Race", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.Race), "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.RunnerRaceRecord), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_User_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.Role), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.User), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.RunnerClassification), "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.RunnerRaceRecord), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.RunnerRaceRecord), "RunnerRaceRecord1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CCData.RunnerRaceRecord), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecord_User", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.User), "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.RunnerRaceRecord), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.VarsityLevel), "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.RunnerRaceRecord), true)]
[assembly: EdmRelationshipAttribute("CCModel", "FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCData.RunnerRaceRecord), "RunnerRaceRecordSegment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCData.RunnerRaceRecordSegment), true)]

#endregion

namespace CCData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CCEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CCEntities object using the connection string found in the 'CCEntities' section of the application configuration file.
        /// </summary>
        public CCEntities() : base("name=CCEntities", "CCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CCEntities object.
        /// </summary>
        public CCEntities(string connectionString) : base(connectionString, "CCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CCEntities object.
        /// </summary>
        public CCEntities(EntityConnection connection) : base(connection, "CCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Organization> Organizations
        {
            get
            {
                if ((_Organizations == null))
                {
                    _Organizations = base.CreateObjectSet<Organization>("Organizations");
                }
                return _Organizations;
            }
        }
        private ObjectSet<Organization> _Organizations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Race> Races
        {
            get
            {
                if ((_Races == null))
                {
                    _Races = base.CreateObjectSet<Race>("Races");
                }
                return _Races;
            }
        }
        private ObjectSet<Race> _Races;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RunnerClassification> RunnerClassifications
        {
            get
            {
                if ((_RunnerClassifications == null))
                {
                    _RunnerClassifications = base.CreateObjectSet<RunnerClassification>("RunnerClassifications");
                }
                return _RunnerClassifications;
            }
        }
        private ObjectSet<RunnerClassification> _RunnerClassifications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RunnerRaceRecord> RunnerRaceRecords
        {
            get
            {
                if ((_RunnerRaceRecords == null))
                {
                    _RunnerRaceRecords = base.CreateObjectSet<RunnerRaceRecord>("RunnerRaceRecords");
                }
                return _RunnerRaceRecords;
            }
        }
        private ObjectSet<RunnerRaceRecord> _RunnerRaceRecords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RunnerRaceRecordSegment> RunnerRaceRecordSegments
        {
            get
            {
                if ((_RunnerRaceRecordSegments == null))
                {
                    _RunnerRaceRecordSegments = base.CreateObjectSet<RunnerRaceRecordSegment>("RunnerRaceRecordSegments");
                }
                return _RunnerRaceRecordSegments;
            }
        }
        private ObjectSet<RunnerRaceRecordSegment> _RunnerRaceRecordSegments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VarsityLevel> VarsityLevels
        {
            get
            {
                if ((_VarsityLevels == null))
                {
                    _VarsityLevels = base.CreateObjectSet<VarsityLevel>("VarsityLevels");
                }
                return _VarsityLevels;
            }
        }
        private ObjectSet<VarsityLevel> _VarsityLevels;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Organizations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrganizations(Organization organization)
        {
            base.AddObject("Organizations", organization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Races EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRaces(Race race)
        {
            base.AddObject("Races", race);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RunnerClassifications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRunnerClassifications(RunnerClassification runnerClassification)
        {
            base.AddObject("RunnerClassifications", runnerClassification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RunnerRaceRecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRunnerRaceRecords(RunnerRaceRecord runnerRaceRecord)
        {
            base.AddObject("RunnerRaceRecords", runnerRaceRecord);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RunnerRaceRecordSegments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRunnerRaceRecordSegments(RunnerRaceRecordSegment runnerRaceRecordSegment)
        {
            base.AddObject("RunnerRaceRecordSegments", runnerRaceRecordSegment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VarsityLevels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVarsityLevels(VarsityLevel varsityLevel)
        {
            base.AddObject("VarsityLevels", varsityLevel);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="Organization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Organization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Organization object.
        /// </summary>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Organization CreateOrganization(global::System.Int64 organizationId, global::System.String name)
        {
            Organization organization = new Organization();
            organization.OrganizationId = organizationId;
            organization.Name = name;
            return organization;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                if (_OrganizationId != value)
                {
                    OnOrganizationIdChanging(value);
                    ReportPropertyChanging("OrganizationId");
                    _OrganizationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrganizationId");
                    OnOrganizationIdChanged();
                }
            }
        }
        private global::System.Int64 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int64 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MascotName
        {
            get
            {
                return _MascotName;
            }
            set
            {
                OnMascotNameChanging(value);
                ReportPropertyChanging("MascotName");
                _MascotName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MascotName");
                OnMascotNameChanged();
            }
        }
        private global::System.String _MascotName;
        partial void OnMascotNameChanging(global::System.String value);
        partial void OnMascotNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MascotImageFileLocation
        {
            get
            {
                return _MascotImageFileLocation;
            }
            set
            {
                OnMascotImageFileLocationChanging(value);
                ReportPropertyChanging("MascotImageFileLocation");
                _MascotImageFileLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MascotImageFileLocation");
                OnMascotImageFileLocationChanged();
            }
        }
        private global::System.String _MascotImageFileLocation;
        partial void OnMascotImageFileLocationChanging(global::System.String value);
        partial void OnMascotImageFileLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tagline
        {
            get
            {
                return _Tagline;
            }
            set
            {
                OnTaglineChanging(value);
                ReportPropertyChanging("Tagline");
                _Tagline = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tagline");
                OnTaglineChanged();
            }
        }
        private global::System.String _Tagline;
        partial void OnTaglineChanging(global::System.String value);
        partial void OnTaglineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int64> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnModifiedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_Race_Organization", "Race")]
        public EntityCollection<Race> Races
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Race>("CCModel.FK_Race_Organization", "Race");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Race>("CCModel.FK_Race_Organization", "Race", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_User_Organization", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("CCModel.FK_User_Organization", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("CCModel.FK_User_Organization", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="Race")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Race : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Race object.
        /// </summary>
        /// <param name="raceId">Initial value of the RaceId property.</param>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Race CreateRace(global::System.Int64 raceId, global::System.Int64 organizationId, global::System.String description)
        {
            Race race = new Race();
            race.RaceId = raceId;
            race.OrganizationId = organizationId;
            race.Description = description;
            return race;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RaceId
        {
            get
            {
                return _RaceId;
            }
            set
            {
                if (_RaceId != value)
                {
                    OnRaceIdChanging(value);
                    ReportPropertyChanging("RaceId");
                    _RaceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RaceId");
                    OnRaceIdChanged();
                }
            }
        }
        private global::System.Int64 _RaceId;
        partial void OnRaceIdChanging(global::System.Int64 value);
        partial void OnRaceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                OnOrganizationIdChanging(value);
                ReportPropertyChanging("OrganizationId");
                _OrganizationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrganizationId");
                OnOrganizationIdChanged();
            }
        }
        private global::System.Int64 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int64 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartedOn
        {
            get
            {
                return _StartedOn;
            }
            set
            {
                OnStartedOnChanging(value);
                ReportPropertyChanging("StartedOn");
                _StartedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartedOn");
                OnStartedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartedOn;
        partial void OnStartedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnStartedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CompletedOn
        {
            get
            {
                return _CompletedOn;
            }
            set
            {
                OnCompletedOnChanging(value);
                ReportPropertyChanging("CompletedOn");
                _CompletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompletedOn");
                OnCompletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CompletedOn;
        partial void OnCompletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCompletedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int64> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnModifiedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_Race_Organization", "Organization")]
        public Organization Organization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_Race_Organization", "Organization").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_Race_Organization", "Organization").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Organization> OrganizationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_Race_Organization", "Organization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Organization>("CCModel.FK_Race_Organization", "Organization", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_Race", "RunnerRaceRecord")]
        public EntityCollection<RunnerRaceRecord> RunnerRaceRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_Race", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_Race", "RunnerRaceRecord", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="roleName">Initial value of the RoleName property.</param>
        public static Role CreateRole(global::System.Int32 roleId, global::System.String roleName)
        {
            Role role = new Role();
            role.RoleId = roleId;
            role.RoleName = roleName;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_User_Role", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("CCModel.FK_User_Role", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("CCModel.FK_User_Role", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="RunnerClassification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RunnerClassification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RunnerClassification object.
        /// </summary>
        /// <param name="runnerClassificationId">Initial value of the RunnerClassificationId property.</param>
        /// <param name="runnerClassificationName">Initial value of the RunnerClassificationName property.</param>
        public static RunnerClassification CreateRunnerClassification(global::System.Int32 runnerClassificationId, global::System.String runnerClassificationName)
        {
            RunnerClassification runnerClassification = new RunnerClassification();
            runnerClassification.RunnerClassificationId = runnerClassificationId;
            runnerClassification.RunnerClassificationName = runnerClassificationName;
            return runnerClassification;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RunnerClassificationId
        {
            get
            {
                return _RunnerClassificationId;
            }
            set
            {
                if (_RunnerClassificationId != value)
                {
                    OnRunnerClassificationIdChanging(value);
                    ReportPropertyChanging("RunnerClassificationId");
                    _RunnerClassificationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RunnerClassificationId");
                    OnRunnerClassificationIdChanged();
                }
            }
        }
        private global::System.Int32 _RunnerClassificationId;
        partial void OnRunnerClassificationIdChanging(global::System.Int32 value);
        partial void OnRunnerClassificationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RunnerClassificationName
        {
            get
            {
                return _RunnerClassificationName;
            }
            set
            {
                OnRunnerClassificationNameChanging(value);
                ReportPropertyChanging("RunnerClassificationName");
                _RunnerClassificationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RunnerClassificationName");
                OnRunnerClassificationNameChanged();
            }
        }
        private global::System.String _RunnerClassificationName;
        partial void OnRunnerClassificationNameChanging(global::System.String value);
        partial void OnRunnerClassificationNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_RunnerClassification", "RunnerRaceRecord")]
        public EntityCollection<RunnerRaceRecord> RunnerRaceRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerRaceRecord", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="RunnerRaceRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RunnerRaceRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RunnerRaceRecord object.
        /// </summary>
        /// <param name="runnerRaceRecordId">Initial value of the RunnerRaceRecordId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="raceId">Initial value of the RaceId property.</param>
        /// <param name="runnerClassificationId">Initial value of the RunnerClassificationId property.</param>
        /// <param name="varsityLevelId">Initial value of the VarsityLevelId property.</param>
        public static RunnerRaceRecord CreateRunnerRaceRecord(global::System.Int64 runnerRaceRecordId, global::System.Int64 userId, global::System.Int64 raceId, global::System.Int32 runnerClassificationId, global::System.Int32 varsityLevelId)
        {
            RunnerRaceRecord runnerRaceRecord = new RunnerRaceRecord();
            runnerRaceRecord.RunnerRaceRecordId = runnerRaceRecordId;
            runnerRaceRecord.UserId = userId;
            runnerRaceRecord.RaceId = raceId;
            runnerRaceRecord.RunnerClassificationId = runnerClassificationId;
            runnerRaceRecord.VarsityLevelId = varsityLevelId;
            return runnerRaceRecord;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RunnerRaceRecordId
        {
            get
            {
                return _RunnerRaceRecordId;
            }
            set
            {
                if (_RunnerRaceRecordId != value)
                {
                    OnRunnerRaceRecordIdChanging(value);
                    ReportPropertyChanging("RunnerRaceRecordId");
                    _RunnerRaceRecordId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RunnerRaceRecordId");
                    OnRunnerRaceRecordIdChanged();
                }
            }
        }
        private global::System.Int64 _RunnerRaceRecordId;
        partial void OnRunnerRaceRecordIdChanging(global::System.Int64 value);
        partial void OnRunnerRaceRecordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RaceId
        {
            get
            {
                return _RaceId;
            }
            set
            {
                OnRaceIdChanging(value);
                ReportPropertyChanging("RaceId");
                _RaceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RaceId");
                OnRaceIdChanged();
            }
        }
        private global::System.Int64 _RaceId;
        partial void OnRaceIdChanging(global::System.Int64 value);
        partial void OnRaceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RunnerClassificationId
        {
            get
            {
                return _RunnerClassificationId;
            }
            set
            {
                OnRunnerClassificationIdChanging(value);
                ReportPropertyChanging("RunnerClassificationId");
                _RunnerClassificationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RunnerClassificationId");
                OnRunnerClassificationIdChanged();
            }
        }
        private global::System.Int32 _RunnerClassificationId;
        partial void OnRunnerClassificationIdChanging(global::System.Int32 value);
        partial void OnRunnerClassificationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VarsityLevelId
        {
            get
            {
                return _VarsityLevelId;
            }
            set
            {
                OnVarsityLevelIdChanging(value);
                ReportPropertyChanging("VarsityLevelId");
                _VarsityLevelId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VarsityLevelId");
                OnVarsityLevelIdChanged();
            }
        }
        private global::System.Int32 _VarsityLevelId;
        partial void OnVarsityLevelIdChanging(global::System.Int32 value);
        partial void OnVarsityLevelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int64> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnModifiedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_Race", "Race")]
        public Race Race
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("CCModel.FK_RunnerRaceRecord_Race", "Race").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("CCModel.FK_RunnerRaceRecord_Race", "Race").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Race> RaceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Race>("CCModel.FK_RunnerRaceRecord_Race", "Race");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Race>("CCModel.FK_RunnerRaceRecord_Race", "Race", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification")]
        public RunnerClassification RunnerClassification
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerClassification>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerClassification>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RunnerClassification> RunnerClassificationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerClassification>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RunnerClassification>("CCModel.FK_RunnerRaceRecord_RunnerClassification", "RunnerClassification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord1")]
        public RunnerRaceRecord RunnerRaceRecord1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RunnerRaceRecord> RunnerRaceRecord1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord")]
        public RunnerRaceRecord RunnerRaceRecord2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RunnerRaceRecord> RunnerRaceRecord2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_RunnerRaceRecord", "RunnerRaceRecord", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_User", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CCModel.FK_RunnerRaceRecord_User", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CCModel.FK_RunnerRaceRecord_User", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("CCModel.FK_RunnerRaceRecord_User", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("CCModel.FK_RunnerRaceRecord_User", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel")]
        public VarsityLevel VarsityLevel
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VarsityLevel>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VarsityLevel>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VarsityLevel> VarsityLevelReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VarsityLevel>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VarsityLevel>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "VarsityLevel", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecordSegment")]
        public EntityCollection<RunnerRaceRecordSegment> RunnerRaceRecordSegments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RunnerRaceRecordSegment>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecordSegment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RunnerRaceRecordSegment>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecordSegment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="RunnerRaceRecordSegment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RunnerRaceRecordSegment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RunnerRaceRecordSegment object.
        /// </summary>
        /// <param name="runnerRaceRecordSegmentId">Initial value of the RunnerRaceRecordSegmentId property.</param>
        /// <param name="runnerRaceRecordId">Initial value of the RunnerRaceRecordId property.</param>
        public static RunnerRaceRecordSegment CreateRunnerRaceRecordSegment(global::System.Int64 runnerRaceRecordSegmentId, global::System.Int64 runnerRaceRecordId)
        {
            RunnerRaceRecordSegment runnerRaceRecordSegment = new RunnerRaceRecordSegment();
            runnerRaceRecordSegment.RunnerRaceRecordSegmentId = runnerRaceRecordSegmentId;
            runnerRaceRecordSegment.RunnerRaceRecordId = runnerRaceRecordId;
            return runnerRaceRecordSegment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RunnerRaceRecordSegmentId
        {
            get
            {
                return _RunnerRaceRecordSegmentId;
            }
            set
            {
                if (_RunnerRaceRecordSegmentId != value)
                {
                    OnRunnerRaceRecordSegmentIdChanging(value);
                    ReportPropertyChanging("RunnerRaceRecordSegmentId");
                    _RunnerRaceRecordSegmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RunnerRaceRecordSegmentId");
                    OnRunnerRaceRecordSegmentIdChanged();
                }
            }
        }
        private global::System.Int64 _RunnerRaceRecordSegmentId;
        partial void OnRunnerRaceRecordSegmentIdChanging(global::System.Int64 value);
        partial void OnRunnerRaceRecordSegmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RunnerRaceRecordId
        {
            get
            {
                return _RunnerRaceRecordId;
            }
            set
            {
                OnRunnerRaceRecordIdChanging(value);
                ReportPropertyChanging("RunnerRaceRecordId");
                _RunnerRaceRecordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RunnerRaceRecordId");
                OnRunnerRaceRecordIdChanged();
            }
        }
        private global::System.Int64 _RunnerRaceRecordId;
        partial void OnRunnerRaceRecordIdChanging(global::System.Int64 value);
        partial void OnRunnerRaceRecordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int64> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnModifiedByChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord")]
        public RunnerRaceRecord RunnerRaceRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RunnerRaceRecord> RunnerRaceRecordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecordSegment_RunnerRaceRecord", "RunnerRaceRecord", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="organizationId">Initial value of the OrganizationId property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="firstname">Initial value of the Firstname property.</param>
        /// <param name="lastname">Initial value of the Lastname property.</param>
        /// <param name="eligibleForRaces">Initial value of the EligibleForRaces property.</param>
        public static User CreateUser(global::System.Int64 userId, global::System.Int32 roleId, global::System.Int64 organizationId, global::System.String username, global::System.String password, global::System.String firstname, global::System.String lastname, global::System.Boolean eligibleForRaces)
        {
            User user = new User();
            user.UserId = userId;
            user.RoleId = roleId;
            user.OrganizationId = organizationId;
            user.Username = username;
            user.Password = password;
            user.Firstname = firstname;
            user.Lastname = lastname;
            user.EligibleForRaces = eligibleForRaces;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                OnRoleIdChanging(value);
                ReportPropertyChanging("RoleId");
                _RoleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleId");
                OnRoleIdChanged();
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OrganizationId
        {
            get
            {
                return _OrganizationId;
            }
            set
            {
                OnOrganizationIdChanging(value);
                ReportPropertyChanging("OrganizationId");
                _OrganizationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrganizationId");
                OnOrganizationIdChanged();
            }
        }
        private global::System.Int64 _OrganizationId;
        partial void OnOrganizationIdChanging(global::System.Int64 value);
        partial void OnOrganizationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lastname
        {
            get
            {
                return _Lastname;
            }
            set
            {
                OnLastnameChanging(value);
                ReportPropertyChanging("Lastname");
                _Lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lastname");
                OnLastnameChanged();
            }
        }
        private global::System.String _Lastname;
        partial void OnLastnameChanging(global::System.String value);
        partial void OnLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Middlename
        {
            get
            {
                return _Middlename;
            }
            set
            {
                OnMiddlenameChanging(value);
                ReportPropertyChanging("Middlename");
                _Middlename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Middlename");
                OnMiddlenameChanged();
            }
        }
        private global::System.String _Middlename;
        partial void OnMiddlenameChanging(global::System.String value);
        partial void OnMiddlenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GraduationYear
        {
            get
            {
                return _GraduationYear;
            }
            set
            {
                OnGraduationYearChanging(value);
                ReportPropertyChanging("GraduationYear");
                _GraduationYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GraduationYear");
                OnGraduationYearChanged();
            }
        }
        private global::System.String _GraduationYear;
        partial void OnGraduationYearChanging(global::System.String value);
        partial void OnGraduationYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedOn
        {
            get
            {
                return _CreatedOn;
            }
            set
            {
                OnCreatedOnChanging(value);
                ReportPropertyChanging("CreatedOn");
                _CreatedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedOn");
                OnCreatedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedOn;
        partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private Nullable<global::System.Int64> _CreatedBy;
        partial void OnCreatedByChanging(Nullable<global::System.Int64> value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedOn
        {
            get
            {
                return _ModifiedOn;
            }
            set
            {
                OnModifiedOnChanging(value);
                ReportPropertyChanging("ModifiedOn");
                _ModifiedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedOn");
                OnModifiedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedOn;
        partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private Nullable<global::System.Int64> _ModifiedBy;
        partial void OnModifiedByChanging(Nullable<global::System.Int64> value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EligibleForRaces
        {
            get
            {
                return _EligibleForRaces;
            }
            set
            {
                OnEligibleForRacesChanging(value);
                ReportPropertyChanging("EligibleForRaces");
                _EligibleForRaces = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EligibleForRaces");
                OnEligibleForRacesChanged();
            }
        }
        private global::System.Boolean _EligibleForRaces;
        partial void OnEligibleForRacesChanging(global::System.Boolean value);
        partial void OnEligibleForRacesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_User_Organization", "Organization")]
        public Organization Organization
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_User_Organization", "Organization").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_User_Organization", "Organization").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Organization> OrganizationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Organization>("CCModel.FK_User_Organization", "Organization");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Organization>("CCModel.FK_User_Organization", "Organization", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_User_Role", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("CCModel.FK_User_Role", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("CCModel.FK_User_Role", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("CCModel.FK_User_Role", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("CCModel.FK_User_Role", "Role", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_User", "RunnerRaceRecord")]
        public EntityCollection<RunnerRaceRecord> RunnerRaceRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_User", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_User", "RunnerRaceRecord", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CCModel", Name="VarsityLevel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VarsityLevel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VarsityLevel object.
        /// </summary>
        /// <param name="varsityLevelId">Initial value of the VarsityLevelId property.</param>
        /// <param name="varsityLevelName">Initial value of the VarsityLevelName property.</param>
        public static VarsityLevel CreateVarsityLevel(global::System.Int32 varsityLevelId, global::System.String varsityLevelName)
        {
            VarsityLevel varsityLevel = new VarsityLevel();
            varsityLevel.VarsityLevelId = varsityLevelId;
            varsityLevel.VarsityLevelName = varsityLevelName;
            return varsityLevel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VarsityLevelId
        {
            get
            {
                return _VarsityLevelId;
            }
            set
            {
                if (_VarsityLevelId != value)
                {
                    OnVarsityLevelIdChanging(value);
                    ReportPropertyChanging("VarsityLevelId");
                    _VarsityLevelId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VarsityLevelId");
                    OnVarsityLevelIdChanged();
                }
            }
        }
        private global::System.Int32 _VarsityLevelId;
        partial void OnVarsityLevelIdChanging(global::System.Int32 value);
        partial void OnVarsityLevelIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VarsityLevelName
        {
            get
            {
                return _VarsityLevelName;
            }
            set
            {
                OnVarsityLevelNameChanging(value);
                ReportPropertyChanging("VarsityLevelName");
                _VarsityLevelName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VarsityLevelName");
                OnVarsityLevelNameChanged();
            }
        }
        private global::System.String _VarsityLevelName;
        partial void OnVarsityLevelNameChanging(global::System.String value);
        partial void OnVarsityLevelNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CCModel", "FK_RunnerRaceRecord_VarsityLevel", "RunnerRaceRecord")]
        public EntityCollection<RunnerRaceRecord> RunnerRaceRecords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "RunnerRaceRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RunnerRaceRecord>("CCModel.FK_RunnerRaceRecord_VarsityLevel", "RunnerRaceRecord", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
